### ISSUE TITLE
3 tote auto doesn't work

### ISSUE THREAD

**Issue by bobbysq** [frc4646/frc4646-2015-competition-code#3]
We should try to figure out why it doesn't intake the tote properly.

**Comment by ForeverFreed** [comment]
It needs to be running the intakes while it moves forward towards the 2nd tote. As soon as it's about 1/4 around the tote, it needs to stop, giving it just enough time to lose momentum. When it's 1/4 around the tote, then it needs to grab intakes. Since it already has intakes running, it will suck the tote in, and then it can set the 1st tote on top, release, go down, grab the 2nd tote, lift, and then do it all again for the 3rd. How does that sound? I think the ultrasonic sensor might be good for this, because the gyro doesn't detect how far it's gone, and the encoders are crazy unreliable. I know, I know, the ultrasonic is a horrible idea because it doesn't get exact distances, but it could be used for relative distances. Maybe some type of limit switch that tells when it's touching the tote, if the ultrasonic doesn't work?

**Comment by bobbysq** [comment]
Closed because it's canceled.
